openapi: 3.0.3
info:
  title: Ingredients & Dishes API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:

  /ingredients:
    get:
      responses:
        200:
          description: List of ingredients returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

  /ingredients/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Ingredient returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        404:
          description: Not found
          content:
            text/plain:
              schema:
                type: string
                example: "Ingredient.id={id} is not found"

  /ingredients/{id}/stock:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

        - name: at
          in: query
          required: true
          schema:
            type: string
            format: date-time

        - name: unit
          in: query
          required: true
          schema:
            type: string
            enum: [PCS, KG, L]

      responses:
        200:
          description: Stock retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'

        400:
          description: Missing parameters
          content:
            text/plain:
              schema:
                type: string
                example: "Either mandatory query parameter `at` or `unit` is not provided."

        404:
          description: Not found
          content:
            text/plain:
              schema:
                type: string
                example: "Ingredient.id={id} is not found"

  /dishes:
    get:
      responses:
        200:
          description: Dishes list returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'

  /dishes/{id}/ingredients:
    put:
      summary: Associate or dissociate ingredients to a dish
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ingredient'

      responses:
        200:
          description: Updated successfully

        400:
          description: Request body missing
          content:
            text/plain:
              schema:
                type: string
                example: "Request body is required."

        404:
          description: Dish not found
          content:
            text/plain:
              schema:
                type: string
                example: "Dish.id={id} is not found"

components:
  schemas:

    Ingredient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          type: string
        price:
          type: number

    Stock:
      type: object
      properties:
        unit:
          type: string
          enum: [PCS, KG, L]
        value:
          type: number

    Dish:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        selling_price:
          type: number
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'